-- Funcoes utilizadas por constraints/triggers das tabelas abaixo.
CREATE OR REPLACE FUNCTION public.jsonb_is_positive_int_array(payload JSONB)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    jsonb_typeof(payload) = 'array'
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(payload) AS item(value)
      WHERE jsonb_typeof(value) <> 'number'
         OR value::text !~ '^[1-9][0-9]*$'
    );
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TABLE "access_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint,
	"user_email" varchar(160) NOT NULL,
	"ip_origem" varchar(64),
	"user_agent" varchar(512),
	"browser" varchar(120),
	"status" varchar(16) DEFAULT 'SUCESSO' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agenda_bloqueios" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agenda_bloqueios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"profissional_id" bigint NOT NULL,
	"data" date NOT NULL,
	"hora_inicio" time NOT NULL,
	"hora_fim" time NOT NULL,
	"observacoes" text,
	"created_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anamnese" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anamnese_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"paciente_id" bigint NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anamnese_versions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anamnese_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"paciente_id" bigint NOT NULL,
	"version" integer NOT NULL,
	"status" varchar(20) DEFAULT 'Rascunho' NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "atendimentos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "atendimentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"paciente_id" bigint NOT NULL,
	"profissional_id" bigint NOT NULL,
	"data" date NOT NULL,
	"hora_inicio" time NOT NULL,
	"hora_fim" time NOT NULL,
	"is_grupo" boolean DEFAULT false NOT NULL,
	"turno" varchar(20) DEFAULT 'Matutino' NOT NULL,
	"periodo_inicio" date,
	"periodo_fim" date,
	"presenca" varchar(20) DEFAULT 'Nao informado' NOT NULL,
	"realizado" boolean DEFAULT false NOT NULL,
	"status_repasse" varchar(20) DEFAULT 'Pendente' NOT NULL,
	"resumo_repasse" text,
	"motivo" text,
	"observacoes" text,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_atendimentos_realizado_presenca" CHECK ("atendimentos"."realizado" = ("atendimentos"."presenca" = 'Presente'))
);
--> statement-breakpoint
CREATE TABLE "evolucoes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "evolucoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"paciente_id" bigint NOT NULL,
	"profissional_id" bigint NOT NULL,
	"atendimento_id" bigint,
	"data" date NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint
);
--> statement-breakpoint
CREATE TABLE "paciente_terapia" (
	"paciente_id" bigint NOT NULL,
	"terapia_id" integer NOT NULL,
	CONSTRAINT "pk_paciente_terapia" PRIMARY KEY("paciente_id","terapia_id")
);
--> statement-breakpoint
CREATE TABLE "pacientes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pacientes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"cpf" varchar(11) NOT NULL,
	"data_nascimento" date,
	"convenio" varchar(40) DEFAULT 'Particular' NOT NULL,
	"email" varchar(120),
	"nome_responsavel" varchar(120),
	"telefone" varchar(20),
	"telefone2" varchar(20),
	"nome_mae" varchar(120),
	"nome_pai" varchar(120),
	"sexo" varchar(20),
	"data_inicio" date,
	"foto" varchar(255),
	"laudo" varchar(255),
	"documento" varchar(255),
	"ativo" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"resource" varchar(80) NOT NULL,
	"action" varchar(40) NOT NULL,
	"descricao" text
);
--> statement-breakpoint
CREATE TABLE "prontuario_documentos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prontuario_documentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"paciente_id" bigint NOT NULL,
	"tipo" varchar(40) NOT NULL,
	"version" integer NOT NULL,
	"status" varchar(20) DEFAULT 'Rascunho' NOT NULL,
	"titulo" varchar(180),
	"payload" jsonb NOT NULL,
	"created_by_user_id" bigint,
	"created_by_role" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"role" varchar(32) NOT NULL,
	"permission_id" bigint NOT NULL,
	CONSTRAINT "pk_role_permissions" PRIMARY KEY("role","permission_id")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"slug" varchar(32) PRIMARY KEY NOT NULL,
	"nome" varchar(80) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "terapeutas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "terapeutas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"cpf" varchar(11) NOT NULL,
	"data_nascimento" date,
	"email" varchar(120),
	"telefone" varchar(20),
	"endereco" varchar(255),
	"logradouro" varchar(180),
	"numero" varchar(20),
	"bairro" varchar(120),
	"cidade" varchar(120),
	"cep" varchar(8),
	"especialidade" varchar(80) DEFAULT 'Nao informado' NOT NULL,
	"observacao" text,
	"ativo" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint,
	"usuario_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "terapias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "terapias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(40) NOT NULL,
	CONSTRAINT "terapias_nome_unique" UNIQUE("nome")
);
--> statement-breakpoint
CREATE TABLE "user_paciente_vinculos" (
	"user_id" bigint NOT NULL,
	"paciente_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pk_user_paciente_vinculos" PRIMARY KEY("user_id","paciente_id")
);
--> statement-breakpoint
CREATE TABLE "user_paciente_vinculos_audit" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_paciente_vinculos_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_user_id" bigint,
	"target_user_id" bigint,
	"previous_role" varchar(32),
	"next_role" varchar(32) NOT NULL,
	"removed_paciente_ids" jsonb NOT NULL,
	"reason" varchar(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_user_paciente_vinculos_audit_removed_ids_array" CHECK (jsonb_typeof("user_paciente_vinculos_audit"."removed_paciente_ids") = 'array'),
	CONSTRAINT "ck_user_paciente_vinculos_audit_removed_ids_positive_int" CHECK (public.jsonb_is_positive_int_array("user_paciente_vinculos_audit"."removed_paciente_ids"))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"email" varchar(160) NOT NULL,
	"senha_hash" varchar(255) NOT NULL,
	"role" varchar(32) DEFAULT 'profissional' NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "access_logs" ADD CONSTRAINT "access_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agenda_bloqueios" ADD CONSTRAINT "agenda_bloqueios_profissional_id_terapeutas_id_fk" FOREIGN KEY ("profissional_id") REFERENCES "public"."terapeutas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agenda_bloqueios" ADD CONSTRAINT "agenda_bloqueios_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anamnese" ADD CONSTRAINT "anamnese_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anamnese_versions" ADD CONSTRAINT "anamnese_versions_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atendimentos" ADD CONSTRAINT "atendimentos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atendimentos" ADD CONSTRAINT "atendimentos_profissional_id_terapeutas_id_fk" FOREIGN KEY ("profissional_id") REFERENCES "public"."terapeutas"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atendimentos" ADD CONSTRAINT "atendimentos_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evolucoes" ADD CONSTRAINT "evolucoes_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evolucoes" ADD CONSTRAINT "evolucoes_profissional_id_terapeutas_id_fk" FOREIGN KEY ("profissional_id") REFERENCES "public"."terapeutas"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evolucoes" ADD CONSTRAINT "evolucoes_atendimento_id_atendimentos_id_fk" FOREIGN KEY ("atendimento_id") REFERENCES "public"."atendimentos"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evolucoes" ADD CONSTRAINT "evolucoes_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_terapia" ADD CONSTRAINT "paciente_terapia_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_terapia" ADD CONSTRAINT "paciente_terapia_terapia_id_terapias_id_fk" FOREIGN KEY ("terapia_id") REFERENCES "public"."terapias"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pacientes" ADD CONSTRAINT "pacientes_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prontuario_documentos" ADD CONSTRAINT "prontuario_documentos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prontuario_documentos" ADD CONSTRAINT "prontuario_documentos_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prontuario_documentos" ADD CONSTRAINT "prontuario_documentos_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_roles_slug_fk" FOREIGN KEY ("role") REFERENCES "public"."roles"("slug") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_permissions_id_fk" FOREIGN KEY ("permission_id") REFERENCES "public"."permissions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "terapeutas" ADD CONSTRAINT "terapeutas_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "terapeutas" ADD CONSTRAINT "terapeutas_usuario_id_users_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_paciente_vinculos" ADD CONSTRAINT "user_paciente_vinculos_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_paciente_vinculos" ADD CONSTRAINT "user_paciente_vinculos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_paciente_vinculos_audit" ADD CONSTRAINT "user_paciente_vinculos_audit_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_paciente_vinculos_audit" ADD CONSTRAINT "user_paciente_vinculos_audit_target_user_id_users_id_fk" FOREIGN KEY ("target_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_roles_slug_fk" FOREIGN KEY ("role") REFERENCES "public"."roles"("slug") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_deleted_by_user_id_users_id_fk" FOREIGN KEY ("deleted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_access_logs_created_at" ON "access_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_access_logs_user_id" ON "access_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_access_logs_status_created_at" ON "access_logs" USING btree ("status","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_agenda_bloqueios_prof_data" ON "agenda_bloqueios" USING btree ("profissional_id","data");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_anamnese_paciente" ON "anamnese" USING btree ("paciente_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_anamnese_versions_paciente_version" ON "anamnese_versions" USING btree ("paciente_id","version");--> statement-breakpoint
CREATE INDEX "idx_anamnese_versions_paciente_created" ON "anamnese_versions" USING btree ("paciente_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_atend_paciente" ON "atendimentos" USING btree ("paciente_id");--> statement-breakpoint
CREATE INDEX "idx_atend_profissional" ON "atendimentos" USING btree ("profissional_id");--> statement-breakpoint
CREATE INDEX "idx_atend_data_profissional" ON "atendimentos" USING btree ("data","profissional_id");--> statement-breakpoint
CREATE INDEX "idx_atend_deleted_at" ON "atendimentos" USING btree ("deleted_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_evolucoes_atendimento_ativo" ON "evolucoes" USING btree ("atendimento_id") WHERE "evolucoes"."deleted_at" is null and "evolucoes"."atendimento_id" is not null;--> statement-breakpoint
CREATE INDEX "idx_evolucoes_paciente" ON "evolucoes" USING btree ("paciente_id");--> statement-breakpoint
CREATE INDEX "idx_evolucoes_profissional" ON "evolucoes" USING btree ("profissional_id");--> statement-breakpoint
CREATE INDEX "idx_evolucoes_data" ON "evolucoes" USING btree ("data");--> statement-breakpoint
CREATE INDEX "idx_evolucoes_deleted_at" ON "evolucoes" USING btree ("deleted_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_pacientes_cpf_ativo" ON "pacientes" USING btree ("cpf") WHERE "pacientes"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "idx_pacientes_nome" ON "pacientes" USING btree ("nome");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_permissions_resource_action" ON "permissions" USING btree ("resource","action");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_prontuario_documentos_paciente_tipo_version" ON "prontuario_documentos" USING btree ("paciente_id","tipo","version");--> statement-breakpoint
CREATE INDEX "idx_prontuario_documentos_paciente" ON "prontuario_documentos" USING btree ("paciente_id");--> statement-breakpoint
CREATE INDEX "idx_prontuario_documentos_tipo" ON "prontuario_documentos" USING btree ("tipo");--> statement-breakpoint
CREATE INDEX "idx_prontuario_documentos_created_at" ON "prontuario_documentos" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_prontuario_documentos_updated_at" ON "prontuario_documentos" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_prontuario_documentos_deleted_at" ON "prontuario_documentos" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_role_permissions_role" ON "role_permissions" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_role_permissions_permission" ON "role_permissions" USING btree ("permission_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_terapeutas_cpf_ativo" ON "terapeutas" USING btree ("cpf") WHERE "terapeutas"."deleted_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "uk_terapeutas_usuario_ativo" ON "terapeutas" USING btree ("usuario_id") WHERE "terapeutas"."deleted_at" is null and "terapeutas"."usuario_id" is not null;--> statement-breakpoint
CREATE INDEX "idx_terapeutas_usuario" ON "terapeutas" USING btree ("usuario_id");--> statement-breakpoint
CREATE INDEX "idx_terapeutas_nome" ON "terapeutas" USING btree ("nome");--> statement-breakpoint
CREATE INDEX "idx_terapeutas_deleted_at" ON "terapeutas" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_user_paciente_vinculos_paciente" ON "user_paciente_vinculos" USING btree ("paciente_id");--> statement-breakpoint
CREATE INDEX "idx_user_paciente_vinc_audit_target" ON "user_paciente_vinculos_audit" USING btree ("target_user_id");--> statement-breakpoint
CREATE INDEX "idx_user_paciente_vinc_audit_actor" ON "user_paciente_vinculos_audit" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "idx_user_paciente_vinc_audit_created_at" ON "user_paciente_vinculos_audit" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_users_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_users_deleted_at" ON "users" USING btree ("deleted_at");--> statement-breakpoint
CREATE TRIGGER trg_users_set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_pacientes_set_updated_at BEFORE UPDATE ON public.pacientes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_user_paciente_vinculos_set_updated_at BEFORE UPDATE ON public.user_paciente_vinculos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_terapeutas_set_updated_at BEFORE UPDATE ON public.terapeutas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_atendimentos_set_updated_at BEFORE UPDATE ON public.atendimentos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_anamnese_set_updated_at BEFORE UPDATE ON public.anamnese FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_prontuario_documentos_set_updated_at BEFORE UPDATE ON public.prontuario_documentos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
CREATE TRIGGER trg_evolucoes_set_updated_at BEFORE UPDATE ON public.evolucoes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
